# Generated by Django 5.2 on 2025-04-20 10:51

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('events', 'Category')
    for name in ['Cat 1', 'Cat 2', 'Cat 3']:
        Category.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_code=migrations.RunPython.noop),
    ]
